// REDUX ACTION TYPES
export const ADD_ACTIVITY = 'ADD_ACTIVITY' 
export const ADD_ACTIVITY_SUCCESS = 'ADD_ACTIVITY_SUCCESS'
export const ADD_ACTIVITY_FAILURE = 'ADD_ACTIVITY_FAILURE'
export const SET_TEXT = 'SET_TEXT'
