// APP
export const SET_TAB = 'SET_TAB'

// ACTIVITIES
export const ADD_ACTIVITY_STARTED = 'ADD_ACTIVITY_STARTED' 
export const ADD_ACTIVITY_SUCCESS = 'ADD_ACTIVITY_SUCCESS'
export const ADD_ACTIVITY_FAILURE = 'ADD_ACTIVITY_FAILURE'
export const DELETE_ACTIVITY_STARTED = 'DELETE_ACTIVITY_STARTED' 
export const DELETE_ACTIVITY_SUCCESS = 'DELETE_ACTIVITY_SUCCESS'
export const DELETE_ACTIVITY_FAILURE = 'DELETE_ACTIVITY_FAILURE'
export const GET_ACTIVITIES_STARTED = 'GET_ACTIVITIES_STARTED' 
export const GET_ACTIVITIES_SUCCESS = 'GET_ACTIVITIES_SUCCESS'
export const GET_ACTIVITIES_FAILURE = 'GET_ACTIVITIES_FAILURE'
export const SET_ACTIVITIES_FILTER = 'SET_ACTIVITIES_FILTER'
export const LISTEN_ACTIVITIES_STARTED = 'LISTEN_ACTIVITIES_STARTED'
export const LISTEN_ACTIVITIES_SUCCESS = 'LISTEN_ACTIVITIES_SUCCESS'
export const LISTEN_ACTIVITIES_FAILURE = 'LISTEN_ACTIVITIES_FAILURE'